alter table if exists admin
    drop constraint if exists FK448t48dh2cgm67x7iebvs5tw4;
alter table if exists employer
    drop constraint if exists FKbg6hipjygdhcirhdpkqc2m4bl;
alter table if exists file_info
    drop constraint if exists FKavbk78b5isadgk1x6chgagoyh;
alter table if exists student
    drop constraint if exists FK1q5ynguq8ryt6rqs4r7n3w63o;
alter table if exists student
    drop constraint if exists FK6f0po3xl0vk8motj9g2hxqcp7;
alter table if exists student
    drop constraint if exists FK3mphcmldvs29jl1w40ssg300j;
alter table if exists student
    drop constraint if exists FK98mvrg4ch8fyalcqetm9gflr8;
alter table if exists student_inviting_employers
    drop constraint if exists FKd50o3p64bloaalk8p42nhj9v9;
alter table if exists student_inviting_employers
    drop constraint if exists FK3bjpm6v5g7u4l7tu9engs4icd;
alter table if exists student_tag_set
    drop constraint if exists FKn5suc56h33rdfu5dw5iyfeueo;
alter table if exists student_tag_set
    drop constraint if exists FKr3o07dptk4g8snudej3petbal;
alter table if exists teacher
    drop constraint if exists FKhinn6d19xqhlw148yieb71qpp;
drop table if exists admin cascade;
drop table if exists employer cascade;
drop table if exists file_info cascade;
drop table if exists student cascade;
drop table if exists student_inviting_employers cascade;
drop table if exists student_tag_set cascade;
drop table if exists tag cascade;
drop table if exists teacher cascade;
drop table if exists user_model cascade;
create table admin
(
    id int8 not null,
    primary key (id)
);
create table employer
(
    company_name varchar(255) not null,
    phone_number varchar(255) not null,
    id           int8         not null,
    primary key (id)
);
create table file_info
(
    id                int8 generated by default as identity,
    created_at        date,
    original_filename varchar(255),
    size              int8,
    storage_filename  varchar(255),
    type              varchar(255),
    url               varchar(255),
    user_id           int8,
    primary key (id)
);
create table student
(
    competence       varchar(255),
    competence_state varchar(255) not null,
    course           int4         not null,
    group_number     int4         not null,
    name             varchar(255) not null,
    patronymic       varchar(255) not null,
    surname          varchar(255) not null,
    id               int8         not null,
    employer_id      int8,
    main_photo_id    int8,
    teacher_id       int8,
    primary key (id)
);
create table student_inviting_employers
(
    invited_students_id   int8 not null,
    inviting_employers_id int8 not null,
    primary key (invited_students_id, inviting_employers_id)
);
create table student_tag_set
(
    student_set_id int8 not null,
    tag_set_id     int8 not null,
    primary key (student_set_id, tag_set_id)
);
create table tag
(
    id       int8 generated by default as identity,
    tag_name varchar(255) not null,
    primary key (id)
);
create table teacher
(
    addition_information   varchar(255),
    education              varchar(255),
    knowledge_of_languages varchar(255),
    name                   varchar(255) not null,
    patronymic             varchar(255) not null,
    position_held          varchar(255),
    surname                varchar(255) not null,
    id                     int8         not null,
    primary key (id)
);
create table user_model
(
    id            int8 generated by default as identity,
    hash_password varchar(255) not null,
    mail          varchar(255) not null,
    role          varchar(255) not null,
    state         varchar(255) not null,
    primary key (id)
);
alter table if exists tag
    add constraint UK_1r1tyf6uga9k6jwdqnoqwtk2a unique (tag_name);
alter table if exists user_model
    add constraint UK_7fcmaam8u45o0adkdhbtf0556 unique (mail);
alter table if exists admin
    add constraint FK448t48dh2cgm67x7iebvs5tw4 foreign key (id) references user_model;
alter table if exists employer
    add constraint FKbg6hipjygdhcirhdpkqc2m4bl foreign key (id) references user_model;
alter table if exists file_info
    add constraint FKavbk78b5isadgk1x6chgagoyh foreign key (user_id) references user_model;
alter table if exists student
    add constraint FK1q5ynguq8ryt6rqs4r7n3w63o foreign key (employer_id) references employer;
alter table if exists student
    add constraint FK6f0po3xl0vk8motj9g2hxqcp7 foreign key (main_photo_id) references file_info;
alter table if exists student
    add constraint FK3mphcmldvs29jl1w40ssg300j foreign key (teacher_id) references teacher;
alter table if exists student
    add constraint FK98mvrg4ch8fyalcqetm9gflr8 foreign key (id) references user_model;
alter table if exists student_inviting_employers
    add constraint FKd50o3p64bloaalk8p42nhj9v9 foreign key (inviting_employers_id) references employer;
alter table if exists student_inviting_employers
    add constraint FK3bjpm6v5g7u4l7tu9engs4icd foreign key (invited_students_id) references student;
alter table if exists student_tag_set
    add constraint FKn5suc56h33rdfu5dw5iyfeueo foreign key (tag_set_id) references tag;
alter table if exists student_tag_set
    add constraint FKr3o07dptk4g8snudej3petbal foreign key (student_set_id) references student;
alter table if exists teacher
    add constraint FKhinn6d19xqhlw148yieb71qpp foreign key (id) references user_model;